/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type V_Content = V_RawContent | V_LineContent | V_RubyContent | V_SupContent | V_SubContent;
export type Contenttype = "raw";
export type Content = string;
export type Contenttype1 = "line";
export type Style = "dotted" | "double" | "none" | "solid";
export type V_UnderlinedContent =
  | V_RawContent
  | V_QuateStructContent
  | V_ArithFormulaContent
  | V_RubyContent
  | V_SupContent
  | V_SubContent;
export type Contenttype2 = "quoteStruct";
export type V_Content1 = V_RawContent | V_LineContent | V_RubyContent | V_SupContent | V_SubContent;
export type Contenttype3 = "ruby";
export type Valuetype = "rt" | "rb";
export type Value = string;
export type Content2 = V_InnerRuby[];
export type Contenttype4 = "sup";
export type Content3 = string;
export type Contenttype5 = "sub";
export type Content4 = string;
export type Content1 = V_Content1[];
export type Contenttype6 = "arithFormula";
export type Content5 = string;
export type Contents = V_UnderlinedContent[];
export type Relatedarticlenum = V_Content[];
export type Title1 = string;
export type RowSpan = number;
export type Num = string;
export type Function = "default" | "main" | "proviso";
export type V_Content2 = V_RawContent | V_LineContent | V_RubyContent | V_SupContent | V_SubContent;
export type Content6 = V_Content2[];
export type Sentences = V_Sentence[];
export type Columns = V_TableColumn[];
export type Rows = V_TableRow[];
export type Tablestructs = V_TableStruct[];

export interface V_AppdxTable {
  title: Title;
  relatedArticleNum: Relatedarticlenum;
  tableStructs: Tablestructs;
  [k: string]: unknown;
}
/**
 * 文字列要素
 */
export interface V_RawContent {
  contentType: Contenttype;
  content: Content;
  [k: string]: unknown;
}
/**
 * 傍線を表す要素
 */
export interface V_LineContent {
  contentType: Contenttype1;
  content: V_InnerLine;
  [k: string]: unknown;
}
/**
 * 傍線を表す要素
 */
export interface V_InnerLine {
  style?: Style;
  contents: Contents;
  [k: string]: unknown;
}
/**
 * 改行を含む構造の引用
 */
export interface V_QuateStructContent {
  contentType: Contenttype2;
  content: Content1;
  [k: string]: unknown;
}
/**
 * ルビ付きの文字列
 */
export interface V_RubyContent {
  contentType: Contenttype3;
  content: Content2;
  [k: string]: unknown;
}
/**
 * ルビ付き文字列の子要素 rtまたはrb
 */
export interface V_InnerRuby {
  valueType: Valuetype;
  value: Value;
  [k: string]: unknown;
}
/**
 * 上付き文字
 */
export interface V_SupContent {
  contentType: Contenttype4;
  content: Content3;
  [k: string]: unknown;
}
/**
 * 下付き文字
 */
export interface V_SubContent {
  contentType: Contenttype5;
  content: Content4;
  [k: string]: unknown;
}
/**
 * 算式を表す要素
 */
export interface V_ArithFormulaContent {
  contentType: Contenttype6;
  content: Content5;
  [k: string]: unknown;
}
export interface V_TableStruct {
  title: Title1;
  table: V_Table;
  [k: string]: unknown;
}
export interface V_Table {
  rows: Rows;
  [k: string]: unknown;
}
export interface V_TableRow {
  columns: Columns;
  [k: string]: unknown;
}
export interface V_TableColumn {
  row_span?: RowSpan;
  sentences: Sentences;
  [k: string]: unknown;
}
export interface V_Sentence {
  num: Num;
  function: Function;
  content: Content6;
  [k: string]: unknown;
}
