/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Num = string;
export type Title = string;
export type Caption = string;
export type Num1 = string;
export type Caption1 = string;
export type Num2 = string;
export type Function = "default" | "main" | "proviso";
export type V_Content = V_RawContent | V_LineContent | V_RubyContent | V_SupContent | V_SubContent;
export type Contenttype = "raw";
export type Content1 = string;
export type Contenttype1 = "line";
export type Style = "dotted" | "double" | "none" | "solid";
export type V_UnderlinedContent =
  | V_RawContent
  | V_QuateStructContent
  | V_ArithFormulaContent
  | V_RubyContent
  | V_SupContent
  | V_SubContent;
export type Contenttype2 = "quoteStruct";
export type V_Content1 = V_RawContent | V_LineContent | V_RubyContent | V_SupContent | V_SubContent;
export type Contenttype3 = "ruby";
export type Valuetype = "rt" | "rb";
export type Value = string;
export type Content3 = V_InnerRuby[];
export type Contenttype4 = "sup";
export type Content4 = string;
export type Contenttype5 = "sub";
export type Content5 = string;
export type Content2 = V_Content1[];
export type Contenttype6 = "arithFormula";
export type Content6 = string;
export type Contents = V_UnderlinedContent[];
export type Content = V_Content[];
export type Sentences = V_Sentence[];
export type Paragraphs = V_Paragraph[];
export type Items = V_Article[];

export interface V_Articles {
  items: Items;
  [k: string]: unknown;
}
export interface V_Article {
  id: Id;
  num: Num;
  title: Title;
  caption: Caption;
  paragraphs: Paragraphs;
  [k: string]: unknown;
}
export interface V_Paragraph {
  num: Num1;
  caption: Caption1;
  paragraphSentence: V_ParagraphSentence;
  [k: string]: unknown;
}
export interface V_ParagraphSentence {
  sentences: Sentences;
  [k: string]: unknown;
}
export interface V_Sentence {
  num: Num2;
  function: Function;
  content: Content;
  [k: string]: unknown;
}
/**
 * 文字列要素
 */
export interface V_RawContent {
  contentType: Contenttype;
  content: Content1;
  [k: string]: unknown;
}
/**
 * 傍線を表す要素
 */
export interface V_LineContent {
  contentType: Contenttype1;
  content: V_InnerLine;
  [k: string]: unknown;
}
/**
 * 傍線を表す要素
 */
export interface V_InnerLine {
  style?: Style;
  contents: Contents;
  [k: string]: unknown;
}
/**
 * 改行を含む構造の引用
 */
export interface V_QuateStructContent {
  contentType: Contenttype2;
  content: Content2;
  [k: string]: unknown;
}
/**
 * ルビ付きの文字列
 */
export interface V_RubyContent {
  contentType: Contenttype3;
  content: Content3;
  [k: string]: unknown;
}
/**
 * ルビ付き文字列の子要素 rtまたはrb
 */
export interface V_InnerRuby {
  valueType: Valuetype;
  value: Value;
  [k: string]: unknown;
}
/**
 * 上付き文字
 */
export interface V_SupContent {
  contentType: Contenttype4;
  content: Content4;
  [k: string]: unknown;
}
/**
 * 下付き文字
 */
export interface V_SubContent {
  contentType: Contenttype5;
  content: Content5;
  [k: string]: unknown;
}
/**
 * 算式を表す要素
 */
export interface V_ArithFormulaContent {
  contentType: Contenttype6;
  content: Content6;
  [k: string]: unknown;
}
